insert into LOCATION_TAG (id, name)
values (1, 'Vormittag'),
       (2, 'Nachmittag'),
       (3, 'Nacht'),
       (4, 'Wiese'),
       (5, 'Keller'),
       (6, 'Party'),
       (7, 'Zimmer'),
       (8, 'Saal'),
       (9, 'Luxuriös'),
       (10, 'Meeting'),
       (11, 'Wohnung'),
       (12, 'Garage'),
       (13, 'Scheune'),
       (14, 'Halle'),
       (15, 'Haus'),
       (16, 'Büro'),
       (17, 'Garten'),
       (18, 'Hütte'),
       (19, 'Hochzeit'),
       (20, 'Geburtstag'),
       (21, 'Dachboden'),
       (22, 'Werkstatt'),
       (23, 'Lager');
