export enum LocationSortingCriterion {
  RECOMMENDED_DESC = 'RECOMMENDED_DESC',
  CREATION_DATE_DESC = 'CREATION_DATE_DESC',
  CREATION_DATE_ASC = 'CREATION_DATE_ASC',
  RATING_DESC = 'RATING_DESC',
  RATING_ASC = 'RATING_ASC',
  SIZE_DESC = 'SIZE_DESC',
  SIZE_ASC = 'SIZE_ASC',
  MIN_PRICE_DESC = 'MIN_PRICE_DESC',
  MIN_PRICE_ASC = 'MIN_PRICE_ASC',
  MAX_PRICE_DESC = 'MAX_PRICE_DESC',
  MAX_PRICE_ASC = 'MAX_PRICE_ASC',
  AVG_PRICE_DESC = 'AVG_PRICE_DESC',
  AVG_PRICE_ASC = 'AVG_PRICE_ASC',
  AMOUNT_OF_RATINGS_DESC = 'AMOUNT_OF_RATINGS_DESC',
  AMOUNT_OF_RATINGS_ASC = 'AMOUNT_OF_RATINGS_ASC',
}

export const sortToDisplayText = {
  RECOMMENDED_DESC: 'Empfehlung',
  CREATION_DATE_DESC: 'Erstellungsdatum (↓)',
  CREATION_DATE_ASC: 'Erstellungsdatum (↑)',
  RATING_DESC: 'Durchschnittlicher Bewertung (↓)',
  RATING_ASC: 'Durchschnittlicher Bewertung (↑)',
  SIZE_DESC: 'Größe (↓)',
  SIZE_ASC: 'Größe (↑)',
  MIN_PRICE_DESC: 'Minimaler Preis (↓)',
  MIN_PRICE_ASC: 'Minimaler Preis (↑)',
  MAX_PRICE_DESC: 'Maximaler Preis (↓)',
  MAX_PRICE_ASC: 'Maximaler Preis (↑)',
  AVG_PRICE_DESC: 'Durchschnittlicher Preis (↓)',
  AVG_PRICE_ASC: 'Durchschnittlicher Preis (↑)',
  AMOUNT_OF_RATINGS_DESC: 'Anzahl an Bewertungen (↓)',
  AMOUNT_OF_RATINGS_ASC: 'Anzahl an Bewertungen (↑)',
};
